# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import two_phase_commit_pb2 as two__phase__commit__pb2


class TwoPhaseCommitCoordinatorStub(object):
    """============================
    COORDINATOR SERVICES
    ============================

    Service for client to initiate transactions with coordinator
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateTransaction = channel.unary_unary(
                '/twopc.TwoPhaseCommitCoordinator/InitiateTransaction',
                request_serializer=two__phase__commit__pb2.TransactionRequest.SerializeToString,
                response_deserializer=two__phase__commit__pb2.TransactionResponse.FromString,
                )


class TwoPhaseCommitCoordinatorServicer(object):
    """============================
    COORDINATOR SERVICES
    ============================

    Service for client to initiate transactions with coordinator
    """

    def InitiateTransaction(self, request, context):
        """Client initiates a distributed transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPhaseCommitCoordinatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateTransaction,
                    request_deserializer=two__phase__commit__pb2.TransactionRequest.FromString,
                    response_serializer=two__phase__commit__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPhaseCommitCoordinator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TwoPhaseCommitCoordinator(object):
    """============================
    COORDINATOR SERVICES
    ============================

    Service for client to initiate transactions with coordinator
    """

    @staticmethod
    def InitiateTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/twopc.TwoPhaseCommitCoordinator/InitiateTransaction',
            two__phase__commit__pb2.TransactionRequest.SerializeToString,
            two__phase__commit__pb2.TransactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ParticipantVotingPhaseStub(object):
    """=====================================================
    PARTICIPANT SERVICES (External - Between Nodes)
    =====================================================

    Service for coordinator to communicate with participant's voting phase
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VoteRequest = channel.unary_unary(
                '/twopc.ParticipantVotingPhase/VoteRequest',
                request_serializer=two__phase__commit__pb2.VoteRequestMessage.SerializeToString,
                response_deserializer=two__phase__commit__pb2.VoteResponseMessage.FromString,
                )


class ParticipantVotingPhaseServicer(object):
    """=====================================================
    PARTICIPANT SERVICES (External - Between Nodes)
    =====================================================

    Service for coordinator to communicate with participant's voting phase
    """

    def VoteRequest(self, request, context):
        """Coordinator sends vote request to participant's voting phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParticipantVotingPhaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VoteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.VoteRequest,
                    request_deserializer=two__phase__commit__pb2.VoteRequestMessage.FromString,
                    response_serializer=two__phase__commit__pb2.VoteResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.ParticipantVotingPhase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ParticipantVotingPhase(object):
    """=====================================================
    PARTICIPANT SERVICES (External - Between Nodes)
    =====================================================

    Service for coordinator to communicate with participant's voting phase
    """

    @staticmethod
    def VoteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/twopc.ParticipantVotingPhase/VoteRequest',
            two__phase__commit__pb2.VoteRequestMessage.SerializeToString,
            two__phase__commit__pb2.VoteResponseMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ParticipantDecisionPhaseStub(object):
    """Service for coordinator to communicate with participant's decision phase
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GlobalDecision = channel.unary_unary(
                '/twopc.ParticipantDecisionPhase/GlobalDecision',
                request_serializer=two__phase__commit__pb2.GlobalDecisionMessage.SerializeToString,
                response_deserializer=two__phase__commit__pb2.DecisionAck.FromString,
                )


class ParticipantDecisionPhaseServicer(object):
    """Service for coordinator to communicate with participant's decision phase
    """

    def GlobalDecision(self, request, context):
        """Coordinator sends final decision to participant's decision phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParticipantDecisionPhaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=two__phase__commit__pb2.GlobalDecisionMessage.FromString,
                    response_serializer=two__phase__commit__pb2.DecisionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.ParticipantDecisionPhase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ParticipantDecisionPhase(object):
    """Service for coordinator to communicate with participant's decision phase
    """

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/twopc.ParticipantDecisionPhase/GlobalDecision',
            two__phase__commit__pb2.GlobalDecisionMessage.SerializeToString,
            two__phase__commit__pb2.DecisionAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class IntraNodeDecisionPhaseStub(object):
    """=======================================================
    INTRA-NODE SERVICES (Within Same Container)
    =======================================================

    Service for voting phase to communicate with decision phase within same node
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyVote = channel.unary_unary(
                '/twopc.IntraNodeDecisionPhase/NotifyVote',
                request_serializer=two__phase__commit__pb2.VoteNotification.SerializeToString,
                response_deserializer=two__phase__commit__pb2.VoteAck.FromString,
                )
        self.ReceiveGlobalDecision = channel.unary_unary(
                '/twopc.IntraNodeDecisionPhase/ReceiveGlobalDecision',
                request_serializer=two__phase__commit__pb2.GlobalDecisionMessage.SerializeToString,
                response_deserializer=two__phase__commit__pb2.DecisionAck.FromString,
                )


class IntraNodeDecisionPhaseServicer(object):
    """=======================================================
    INTRA-NODE SERVICES (Within Same Container)
    =======================================================

    Service for voting phase to communicate with decision phase within same node
    """

    def NotifyVote(self, request, context):
        """Voting phase notifies decision phase about its vote
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveGlobalDecision(self, request, context):
        """Voting phase sends coordinator's decision to decision phase
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntraNodeDecisionPhaseServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyVote': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyVote,
                    request_deserializer=two__phase__commit__pb2.VoteNotification.FromString,
                    response_serializer=two__phase__commit__pb2.VoteAck.SerializeToString,
            ),
            'ReceiveGlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveGlobalDecision,
                    request_deserializer=two__phase__commit__pb2.GlobalDecisionMessage.FromString,
                    response_serializer=two__phase__commit__pb2.DecisionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.IntraNodeDecisionPhase', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntraNodeDecisionPhase(object):
    """=======================================================
    INTRA-NODE SERVICES (Within Same Container)
    =======================================================

    Service for voting phase to communicate with decision phase within same node
    """

    @staticmethod
    def NotifyVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/twopc.IntraNodeDecisionPhase/NotifyVote',
            two__phase__commit__pb2.VoteNotification.SerializeToString,
            two__phase__commit__pb2.VoteAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReceiveGlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/twopc.IntraNodeDecisionPhase/ReceiveGlobalDecision',
            two__phase__commit__pb2.GlobalDecisionMessage.SerializeToString,
            two__phase__commit__pb2.DecisionAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
