# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"1\n\x0bVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\"2\n\x0cVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"8\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\r\n\x05index\x18\x03 \x01(\x05\"\x99\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x1a\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\t.LogEntry\x12\x16\n\x0eprev_log_index\x18\x04 \x01(\x05\x12\x15\n\rprev_log_term\x18\x05 \x01(\x05\x12\x15\n\rleader_commit\x18\x06 \x01(\x05\"K\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x05\"5\n\rClientRequest\x12\x11\n\toperation\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"E\n\x0e\x43lientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tleader_id\x18\x03 \x01(\t2r\n\x04Raft\x12*\n\x0bRequestVote\x12\x0c.VoteRequest\x1a\r.VoteResponse\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse2@\n\nRaftClient\x12\x32\n\x0fSubmitOperation\x12\x0e.ClientRequest\x1a\x0f.ClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=14
  _globals['_VOTEREQUEST']._serialized_end=63
  _globals['_VOTERESPONSE']._serialized_start=65
  _globals['_VOTERESPONSE']._serialized_end=115
  _globals['_LOGENTRY']._serialized_start=117
  _globals['_LOGENTRY']._serialized_end=173
  _globals['_APPENDENTRIESREQUEST']._serialized_start=176
  _globals['_APPENDENTRIESREQUEST']._serialized_end=329
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=331
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=406
  _globals['_CLIENTREQUEST']._serialized_start=408
  _globals['_CLIENTREQUEST']._serialized_end=461
  _globals['_CLIENTRESPONSE']._serialized_start=463
  _globals['_CLIENTRESPONSE']._serialized_end=532
  _globals['_RAFT']._serialized_start=534
  _globals['_RAFT']._serialized_end=648
  _globals['_RAFTCLIENT']._serialized_start=650
  _globals['_RAFTCLIENT']._serialized_end=714
# @@protoc_insertion_point(module_scope)
